<a href="https://colab.research.google.com/github/febinchundakkattiil/numpy/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [230]:
import pandas as pd
s = pd.Series([10,20,30,40,50])
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [231]:
s.dtype

dtype('int64')

In [232]:
s.values

array([10, 20, 30, 40, 50])

In [233]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [234]:
s.name = 'calories'
s

0    10
1    20
2    30
3    40
4    50
Name: calories, dtype: int64

In [235]:
#Indexing
s[0:2]

0    10
1    20
Name: calories, dtype: int64

In [236]:
# iloc -> location based indexing
s.iloc[3]

s.iloc[[1,4,3]]

1    20
4    50
3    40
Name: calories, dtype: int64

In [237]:
index = ["apple","banana" , "grapes" , "orange" , "stawberry"]

In [238]:
s.index = index
s

apple        10
banana       20
grapes       30
orange       40
stawberry    50
Name: calories, dtype: int64

In [239]:
#loc -> label based indexing
s['grapes']

np.int64(30)

NOTE

In label based indexing your start as well as stop value both are included in the output

In [240]:
s['banana'::-1]

banana    20
apple     10
Name: calories, dtype: int64

In [241]:
fruits_protein = {
    "Banana": 1.1,
    "Apple": 0.3,
    "Orange": 0.9,
    "Mango": 0.8,
    "Guava": 2.6,
    "Avocado": 2.0,
    "Blackberries": 1.4,
    "Pomegranate": 1.7,
    "Papaya": 0.5,
    "Grapes": 0.6
}

In [242]:
s2 = pd.Series(fruits_protein,name = 'Proteins')
s2

Banana          1.1
Apple           0.3
Orange          0.9
Mango           0.8
Guava           2.6
Avocado         2.0
Blackberries    1.4
Pomegranate     1.7
Papaya          0.5
Grapes          0.6
Name: Proteins, dtype: float64

In [243]:
# Coditional selection
s2[s2>1]

Banana          1.1
Guava           2.6
Avocado         2.0
Blackberries    1.4
Pomegranate     1.7
Name: Proteins, dtype: float64

In [244]:
#Logical operator & | not

s2[(s2 > 1.5) & (s2 <= 2.5)]

Avocado        2.0
Pomegranate    1.7
Name: Proteins, dtype: float64

In [245]:
s2[(s2 > 1.5) | (s2 > 4)]

Guava          2.6
Avocado        2.0
Pomegranate    1.7
Name: Proteins, dtype: float64

In [246]:
# Modyfing the series

s2['Mango']=10
s2

Banana           1.1
Apple            0.3
Orange           0.9
Mango           10.0
Guava            2.6
Avocado          2.0
Blackberries     1.4
Pomegranate      1.7
Papaya           0.5
Grapes           0.6
Name: Proteins, dtype: float64

In [247]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank", "Grace", "Hannah", "Ian", "Julia"],
    "Age": [24, 30, 22, 28, 26, 35, 21, 29, 33, 27],
    "City": ["Mumbai", "Delhi", "Chennai", "Kolkata", "Bengaluru", "Hyderabad", "Pune", "Ahmedabad", "Jaipur", "Lucknow"]
}

In [248]:
df = pd.DataFrame(data)
df

      Name  Age       City
0    Alice   24     Mumbai
1      Bob   30      Delhi
2  Charlie   22    Chennai
3    David   28    Kolkata
4      Eva   26  Bengaluru
5    Frank   35  Hyderabad
6    Grace   21       Pune
7   Hannah   29  Ahmedabad
8      Ian   33     Jaipur
9    Julia   27    Lucknow

In [249]:
df.head(5)

      Name  Age       City
0    Alice   24     Mumbai
1      Bob   30      Delhi
2  Charlie   22    Chennai
3    David   28    Kolkata
4      Eva   26  Bengaluru

In [250]:
df.tail(3)

     Name  Age       City
7  Hannah   29  Ahmedabad
8     Ian   33     Jaipur
9   Julia   27    Lucknow

In [251]:
#Loc and iloc
df.iloc[1:3]

      Name  Age     City
1      Bob   30    Delhi
2  Charlie   22  Chennai

In [253]:
df.loc[1:3,["Age",'City']]

   Age     City
1   30    Delhi
2   22  Chennai
3   28  Kolkata

In [254]:
df.loc[1:3,["Age",'City',"Name"]]

   Age     City     Name
1   30    Delhi      Bob
2   22  Chennai  Charlie
3   28  Kolkata    David